name: CI/CD LGBT Chat App

on:
  push:
    branches: [ main ]  # Chạy mỗi khi bạn push code lên nhánh main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t lgbt-app-chat .

      - name: Test Docker Run
        run: docker run -d --name test-container lgbt-app-chat